package cd.maichapayteam.zuajob.Tools;

import android.content.Context;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Random;

import cd.maichapayteam.zuajob.Models.Object.User;

public class GeneralClass {

    private static char[] chars = {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'};

    public static Context applicationContext;

    public static User Currentuser = null;

    public static String getRandomPhrase(int nbr) {
        List<String> rep = new ArrayList<>();
        rep.add("le");
        rep.add("mon");
        rep.add("ma");
        rep.add("passer");
        rep.add("notre");
        rep.add("sa");
        rep.add("ta");
        rep.add("saluer");
        rep.add("regarder");
        rep.add("leur");
        rep.add("votre");
        rep.add("gloire");
        rep.add("louange");
        rep.add("honneur");
        rep.add("delivrance");
        rep.add("miracle");
        rep.add("guerrison");
        rep.add("joie");
        rep.add("pleurer");
        rep.add("vanger");
        rep.add("etablir");
        rep.add("dire");
        rep.add("affectionner");
        rep.add("aimer");
        rep.add("comparer");
        rep.add("comparettre");
        rep.add("parler");
        rep.add("adresser");
        rep.add("penser");
        rep.add("papier");
        rep.add("cahier");
        rep.add("telecommande");
        rep.add("decodeur");
        rep.add("couvercle");
        rep.add("table");
        rep.add("monde");
        rep.add("continent");
        rep.add("pays");
        rep.add("ville");
        rep.add("commmune");
        rep.add("avenue");
        rep.add("adresse");
        rep.add("journal");
        rep.add("pantalon");
        rep.add("chemise");
        rep.add("disque");
        rep.add("sac");
        rep.add("rallonge");
        rep.add("prise");
        rep.add("ordinateur");
        rep.add("drap");
        rep.add("television");
        rep.add("chien");
        rep.add("chat");
        rep.add("mur");
        rep.add("chaise");
        rep.add("prier");
        rep.add("enseigne");
        rep.add("precher");
        rep.add("repasser");
        rep.add("fer");
        rep.add("bijoux");
        rep.add("theatre");
        rep.add("film");
        rep.add("date");
        rep.add("numero");
        String response = "";
        for(int j=0; j<nbr; j++) {
            int rand = new Random().nextInt(6) + 4;
            String str = "";
            for (int i = 0; i < rand ; i++) {
                str += rep.get(new Random().nextInt(rep.size())) + " ";
            }
            str = str.trim();
            str += ".";
            str = str.substring(0, 1).toUpperCase() + str.substring(1);
            response += str + " ";
        }
        response = response.trim();
        return response;
    }

    public static User getRandomUser() {
        List<String> prenom = new ArrayList<>();
        prenom.add("Olive");
        prenom.add("Olivier");
        prenom.add("Freddy");
        prenom.add("Fred");
        prenom.add("Fruchance");
        prenom.add("Gath");
        prenom.add("Gael");
        prenom.add("Graziela");
        prenom.add("Gaelle");
        prenom.add("Gracia");
        prenom.add("Glodi");
        prenom.add("Glody");
        prenom.add("Glodie");
        prenom.add("Gloriana");
        prenom.add("Gloria");
        prenom.add("Grady");
        prenom.add("Gadit");
        prenom.add("Helena");
        prenom.add("Helenna");
        prenom.add("Gradie");
        prenom.add("Henock");
        prenom.add("Enock");
        prenom.add("Henrie");
        prenom.add("Honneur");
        prenom.add("Honore");
        prenom.add("Jacob");
        prenom.add("Jeancie");
        prenom.add("Jehiel");
        prenom.add("Jennypher");
        prenom.add("Jennyfer");
        prenom.add("Jenny");
        prenom.add("Jeph");
        prenom.add("Jephte");
        prenom.add("Jeredi");
        prenom.add("Jessi");
        prenom.add("Guyguy");
        prenom.add("Guyslene");
        prenom.add("Guyslain");
        prenom.add("Johny");
        prenom.add("John");
        prenom.add("Jose");
        prenom.add("Joseph");
        prenom.add("Joy");
        prenom.add("Julienne");
        prenom.add("Justine");
        prenom.add("Justina");
        prenom.add("Kevine");
        prenom.add("Kevin");
        prenom.add("Leaticia");
        prenom.add("Landrine");
        prenom.add("Lisa");
        prenom.add("Nana");
        prenom.add("Junola");
        prenom.add("Joel");
        prenom.add("Jeancy");
        prenom.add("Josiane");
        prenom.add("Jeanine");
        prenom.add("Jeacque");
        prenom.add("Metthie");
        prenom.add("Michael");
        prenom.add("Mike");
        prenom.add("Mick");
        prenom.add("Milca");
        prenom.add("Milka");
        prenom.add("Myria");
        prenom.add("Myriam");
        prenom.add("Desire");
        prenom.add("Denis");
        prenom.add("Denise");
        prenom.add("Monic");
        prenom.add("Monique");
        prenom.add("Monica");
        prenom.add("Ercelle");
        prenom.add("Dona");
        prenom.add("Thomas");
        prenom.add("Nadia");
        prenom.add("Nella");
        prenom.add("Nicky");
        prenom.add("Noella");
        prenom.add("Hornella");
        prenom.add("Ornella");
        prenom.add("Pamela");
        prenom.add("Miri");
        prenom.add("Patrice");
        prenom.add("Patricia");
        prenom.add("Paulin");
        prenom.add("Honey");
        prenom.add("Peace");
        prenom.add("Percy");
        prenom.add("Perpetue");
        prenom.add("Plams");
        prenom.add("Princille");
        prenom.add("Prisca");
        prenom.add("Raissa");
        prenom.add("Rebecca");
        prenom.add("Reinita");
        prenom.add("Remedie");
        prenom.add("Rodrick");
        prenom.add("Ruddy");
        prenom.add("Rudy");
        prenom.add("Rupie");
        prenom.add("Sam");
        prenom.add("Samuel");
        prenom.add("Samy");
        prenom.add("Mireille");
        prenom.add("Sarah");
        prenom.add("Sebastien");
        prenom.add("Sephora");
        prenom.add("Serge");
        prenom.add("Sheck");
        prenom.add("Sifa");
        prenom.add("Damaris");
        prenom.add("Eliane");
        prenom.add("Eugenie");
        prenom.add("Jacquie");
        prenom.add("Sirham");
        prenom.add("Stellen");
        prenom.add("Sylvestre");
        prenom.add("Syriane");
        prenom.add("Nobertine");
        prenom.add("Bernadette");
        prenom.add("Thecle");
        prenom.add("Tony");
        prenom.add("Tresor");
        prenom.add("Trickson");
        prenom.add("Triphene");
        prenom.add("Tinis");
        prenom.add("Valerian");
        prenom.add("Valo");
        prenom.add("Vasco");
        prenom.add("Verlin");
        prenom.add("Vernel");
        prenom.add("Viviane");
        prenom.add("Voldie");
        prenom.add("Yan");
        prenom.add("Yannick");
        prenom.add("Yoshua");
        prenom.add("Yvette");
        prenom.add("Nadine");
        prenom.add("Nadege");
        prenom.add("Bijoux");
        prenom.add("Marco");
        prenom.add("Timothee");
        prenom.add("Anny");
        prenom.add("Anita");
        prenom.add("Anaya");
        prenom.add("Nice");
        prenom.add("Stone");
        prenom.add("Steve");
        prenom.add("Rodrigue");
        prenom.add("Chancelvie");
        prenom.add("Chadrack");
        prenom.add("Julvinsi");
        prenom.add("Magloire");
        prenom.add("Justin");
        prenom.add("Merveil");
        prenom.add("Merveille");
        prenom.add("Lydie");
        prenom.add("Andrew");
        prenom.add("Didier");
        prenom.add("Jonathan");
        prenom.add("Judith");
        prenom.add("Junior");
        prenom.add("Miria");
        prenom.add("Miriam");
        prenom.add("Jessica");
        prenom.add("Jessy");
        prenom.add("Jean");
        prenom.add("Nice");
        prenom.add("Merveille");
        prenom.add("Rufus");
        prenom.add("Ethan");
        prenom.add("Orly");
        prenom.add("Charly");
        prenom.add("Chadrack");
        prenom.add("Elikya");
        prenom.add("Elie");
        prenom.add("Helene");
        prenom.add("Markiana");
        prenom.add("Malkia");
        prenom.add("Henry");
        prenom.add("Arnold");
        prenom.add("Cedrick");
        prenom.add("Charlene");
        prenom.add("Esperance");
        prenom.add("Thotho");
        prenom.add("Tantine");
        prenom.add("Valerie");
        prenom.add("Ferdinand");
        prenom.add("Esther");
        prenom.add("Exauce");
        prenom.add("Exaucee");
        prenom.add("Daniel");
        prenom.add("Obed");
        prenom.add("Guy");
        prenom.add("Christiane");
        prenom.add("Ketsia");
        prenom.add("Kerene");
        prenom.add("Abigael");
        prenom.add("Aurelie");
        prenom.add("Alidor");
        prenom.add("Alpha");
        prenom.add("Laetitia");
        prenom.add("Alvine");
        prenom.add("Andy");
        prenom.add("Annie");
        prenom.add("Choisie");
        prenom.add("Christian");
        prenom.add("Deborah");
        prenom.add("Bobo");
        prenom.add("Emile");
        prenom.add("Felix");
        prenom.add("Ibrahim");
        prenom.add("Isso");
        prenom.add("Joyce");
        prenom.add("Matthie");
        prenom.add("Erick");
        prenom.add("Patrick");


        List<String> nom = new ArrayList<>();
        nom.add("Gombolo");
        nom.add("Dongo");
        nom.add("Mbongo");
        nom.add("Kimia");
        nom.add("Mobulu");
        nom.add("Mobutu");
        nom.add("Zanga");
        nom.add("Zengo");
        nom.add("Zalala");
        nom.add("Soloko");
        nom.add("Mesaki");
        nom.add("Senga");
        nom.add("Sakola");
        nom.add("Lika");
        nom.add("Ngiri");
        nom.add("Movenda");
        nom.add("Museko");
        nom.add("Muluba");
        nom.add("Mulalia");
        nom.add("Sikali");
        nom.add("Simba");
        nom.add("Selemani");
        nom.add("Seleka");
        nom.add("Ivoki");
        nom.add("Inkisi");
        nom.add("Lisala");
        nom.add("Lisimbi");
        nom.add("Liksasi");
        nom.add("Likasa");
        nom.add("Lindanda");
        nom.add("Landuku");
        nom.add("Sembola");
        nom.add("Solola");
        nom.add("Selola");
        nom.add("Kavili");
        nom.add("Kiloko");
        nom.add("Kitiki");
        nom.add("Kitinda");
        nom.add("Kiti");
        nom.add("Mesa");
        nom.add("Mansiala");
        nom.add("Mado");
        nom.add("Kamerhe");
        nom.add("Kaningini");
        nom.add("Kaniki");
        nom.add("Kanini");
        nom.add("Kanika");
        nom.add("Kasiki");
        nom.add("Kabibi");
        nom.add("Mbosi");
        nom.add("Malala");
        nom.add("Maki");
        nom.add("Liki");
        nom.add("Leki");
        nom.add("Kati");
        nom.add("Ekolo");
        nom.add("Sakombi");
        nom.add("Savimbi");
        nom.add("Ifoku");
        nom.add("Ingila");
        nom.add("Kovo");
        nom.add("Ifoto");
        nom.add("Ingele");
        nom.add("Engele");
        nom.add("Evele");
        nom.add("Esika");
        nom.add("Elongo");
        nom.add("Elembe");
        nom.add("Eseke");
        nom.add("Esole");
        nom.add("Esakata");
        nom.add("Sakata");
        nom.add("Esobe");
        nom.add("Kalunga");
        nom.add("Mosasa");
        nom.add("Molimo");
        nom.add("Dondola");
        nom.add("Dokolo");
        nom.add("Dololo");
        nom.add("Valela");
        nom.add("Vakasa");
        nom.add("Vanda");
        nom.add("Vondobo");
        nom.add("Vololo");
        nom.add("Vulungu");
        nom.add("Vuzela");
        nom.add("Vungilanga");
        nom.add("Vukoko");
        nom.add("Vulenga");
        nom.add("Vutuka");
        nom.add("Visola");
        nom.add("Vesila");
        nom.add("Vebela");
        nom.add("Velongo");
        nom.add("Vilongo");
        nom.add("Vingila");
        nom.add("Vibila");
        nom.add("Vulambo");
        nom.add("Vumbila");
        nom.add("Vungbo");
        nom.add("Ndiviki");
        nom.add("Ndingari");
        nom.add("Ndika");
        nom.add("Ndobo");
        nom.add("Ndikila");
        nom.add("Ndongala");
        nom.add("Ndisilu");
        nom.add("Ndibu");
        nom.add("Ndabola");
        nom.add("Ndako");
        nom.add("Nduku");
        nom.add("Masiki");
        nom.add("Masisi");
        nom.add("Mbabola");
        nom.add("Mbakana");
        nom.add("Mbekele");
        nom.add("Mbele");
        nom.add("Mbeki");
        nom.add("Masoki");
        nom.add("Mabolo");
        nom.add("Zeleke");
        nom.add("Zongo");
        nom.add("Ndeke");
        nom.add("Matungulu");
        nom.add("Ndembi");
        nom.add("Mbemba");
        nom.add("Mbasala");
        nom.add("Mbabo");
        nom.add("Mololo");
        nom.add("Mosala");
        nom.add("Moseka");
        nom.add("Molaka");
        nom.add("Muyambo");
        nom.add("Mbuyulu");
        nom.add("Mboyo");
        nom.add("Mbo");
        nom.add("Etsu");
        nom.add("Malula");
        nom.add("Saseko");
        nom.add("Masala");
        nom.add("Mangembo");
        nom.add("Bula");
        nom.add("Dekani");
        nom.add("Dimbaboma");
        nom.add("Batetela");
        nom.add("Lubaki");
        nom.add("Zola");
        nom.add("Vazola");
        nom.add("Veseke");
        nom.add("Pandala");
        nom.add("Seleka");
        nom.add("Vanga");
        nom.add("Balo");
        nom.add("Alaba");
        nom.add("Leko");
        nom.add("Sese");
        nom.add("Seko");
        nom.add("Lokolo");
        nom.add("Sasola");
        nom.add("Mabo");
        nom.add("Tshaku");
        nom.add("Tsila");
        nom.add("Loko");
        nom.add("Valu");
        nom.add("Kasha");
        nom.add("Kalengayi");
        nom.add("Kambala");
        nom.add("Katumbi");
        nom.add("Gombo");
        nom.add("Golol");
        nom.add("Sholo");
        nom.add("Alanga");
        nom.add("Sala");
        nom.add("Lula");
        nom.add("Salama");
        nom.add("Soki");
        nom.add("Mpangi");
        nom.add("Mputu");
        nom.add("Bangala");
        nom.add("Bopunga");
        nom.add("Bomongo");
        nom.add("Bonzola");
        nom.add("Kashala");
        nom.add("Kalala");
        nom.add("Kabongo");
        nom.add("Tshamala");
        nom.add("Tshimanga");
        nom.add("Tshisuaka");
        nom.add("Tshilombo");
        nom.add("Tshisekedi");
        nom.add("Fayulu");
        nom.add("Makadi");
        nom.add("Mbuala");
        nom.add("Bakoma");
        nom.add("Kilay");
        nom.add("Tamuzo");
        nom.add("Mwadi");
        nom.add("Mbala");
        nom.add("Nedati");
        nom.add("Mundundu");
        nom.add("Mbuyi");
        nom.add("Mavambu");
        nom.add("Mobambola");
        nom.add("Nlandu");
        nom.add("Boyaka");
        nom.add("Mputu");
        nom.add("Baka");
        nom.add("Bidi");
        nom.add("Ekembe");
        nom.add("Tayaye");
        nom.add("Kibala");
        nom.add("Bizimba");
        nom.add("Lemende");
        nom.add("Elikya");
        nom.add("Khonde");
        nom.add("Miyoto");
        nom.add("Lala");
        nom.add("Balelia");
        nom.add("Toto");
        nom.add("Boki");
        nom.add("Beyana");
        nom.add("Tshibangu");
        nom.add("Luhungu");
        nom.add("Kavbal");
        nom.add("Mangalaboyi");
        nom.add("Hamici");
        nom.add("Masala");
        nom.add("Mpandu");
        nom.add("Milandu");
        nom.add("Mutanga");
        nom.add("Kasongo");
        nom.add("Matosi");
        nom.add("Lopke");
        nom.add("Mampuya");
        nom.add("Matondo");
        nom.add("Mabiala");
        nom.add("Bonoya");
        nom.add("Molangoli");
        nom.add("Wembo");
        nom.add("Dinanga");
        nom.add("Kayiba");
        nom.add("Landu");
        nom.add("Kuku");
        nom.add("Umba");
        nom.add("Nzolo");
        nom.add("Malo");
        nom.add("Mambamika");
        nom.add("Lylas");
        nom.add("BoziBozi");
        nom.add("Kielukusu");
        nom.add("Mayemba");
        nom.add("Bukondo");

        User user = new User();
        //user.remoteId = new Random().nextInt();
        user.setPrenom(prenom.get(new Random().nextInt(prenom.size())));
        user.setNom(nom.get(new Random().nextInt(nom.size())));
        user.setSexe("F");
        if(new Random().nextInt(2)==0) user.setSexe("M");
        //user.birthday = randomDate().toString();
        user.setPhone(String.valueOf(randBetween(890000000, 899999999)));
        user.setPays("DR Congo");
        user.setCodePays("+243");
        user.setEmail(user.getPrenom().toLowerCase() + "." + user.getNom().toLowerCase() + "@gmail.com");
        user.setVille("Kinshasa");
        user.setCommune("Bandal");
        user.setQuartier("Lumumba");
        user.setAdresse("22, M'siri");
        user.setIdentiteVerifie(false);
        if(new Random().nextInt(3) == 0) user.setIdentiteVerifie(true);
        return user;
    }

    public static int randBetween(int start, int end) {
        return start + (int)Math.round(Math.random() * (end - start));
    }

    public static Date randomDate() {
        int year = randBetween(1963, 2004); // generate a year between 1900 and 2010;
        int dayOfYear = randBetween(1, 365); // generate a number between 1 and 365 (or 366 if you need to handle leap year);
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.DAY_OF_YEAR, dayOfYear);
        Date randomDoB = calendar.getTime();
        return randomDoB;
    }

    public static Date randomDate(int minYear, int maxYear) {
        int year = randBetween(minYear, maxYear); // generate a year between 1900 and 2010;
        int dayOfYear = randBetween(1, 365); // generate a number between 1 and 365 (or 366 if you need to handle leap year);
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.DAY_OF_YEAR, dayOfYear);
        Date randomDoB = calendar.getTime();
        return randomDoB;
    }

}
